### ISSUE TITLE
different names on github and npm

### ISSUE THREAD

**Issue by tunnckoCore** [regexhq/es6-template-regex#1]
on npm is `es6-template-regex`, there's no `es6-delimiter-regex` on npm.

/cc @jonschlinkert

**Comment by jonschlinkert** [comment]
will fix

**Comment by jonschlinkert** [comment]
done

**Comment by jonschlinkert** [comment]
sorry about that. looks like everything is named using `templates` on the readme etc. But locally, looks like I had the project in a folder named `es6-delimiters-regex`. I guess I changed my mind lol

**Comment by tunnckoCore** [comment]
:laughing: :+1:
